### ISSUE TITLE
Create a new extention

### ISSUE THREAD

**Issue by mbnoimi** [xtuple/xtdesktop#9]
I'm planning to create a new extension for Qt Client (HR).
Is there any reference to read it before starting up the extension?

BTW, I'm still unable to browse xTuple.com website because of Drupal stupidity so I forced to ask you here instead of the community forums (I browse the Internet behind governmental proxy so if your website forbids my IP that means most people in Libya can't see your website... voila!!!)

P.S. Don't forget I can't read any reference from your website (I downloaded xtuple from sf.net)

**Comment by gilmoskowitz** [comment]
@mbnoimi - try reading https://github.com/xtuple/updater/wiki and https://github.com/xtuple/qt-client/wiki/Hacking-the-xTuple-Desktop-Client-With-Extensions
